curl --request GET \
  --url 'https://sandbox.impala.travel/v1/hotels?country=dfdf' \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: sandb_jqGbRfgERuGdQj7xxlpamMuPOAXPEcbqRubo3xvl'



###
GET https://stoplight.io/mocks/impala/booking-api/4006046/hotels?country=dfdf
# Host: localhost
Host: stoplight.io
Content-type: application/json
x-api-key: sandb_jqGbRfgERuGdQj7xxlpamMuPOAXPEcbqRubo3xvl



###

GET /mocks/impala/booking-api/4006046/hotels?country=dfdf HTTP/3
Host: stoplight.io
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://docs.impala.travel/
Content-Type: application/json
x-api-key: sandb_jqGbRfgERuGdQj7xxlpamMuPOAXPEcbqRubo3xvl
Origin: https://docs.impala.travel
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
TE: trailers
